// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ChallegeContactRecords.WebApi.Entities
{
    public partial class Address
    {
        public Address()
        {
            ContactsRecord = new HashSet<ContactsRecord>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Country { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string States { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string City { get; set; }

        
        public virtual ICollection<ContactsRecord> ContactsRecord { get; set; }
    }
}