// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ChallegeContactRecords.WebApi.Entities
{
    public partial class ContactsRecord
    {
        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string Name { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string Company { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string ProfilePicture { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Email { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string WorkPhoneNumber { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string PersonalPhoneNumber { get; set; }
        public int? AddressID { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string AddressName { get; set; }

        [ForeignKey("AddressID")]
        [InverseProperty("ContactsRecord")]
        public virtual Address Address { get; set; }
    }
}